[project]
name = "some-python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "JAGS", email = "78938133+JoseAngelGarciaSanchez@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
some-python = "some_python:main"

[build-system]
requires = ["uv_build>=0.12.12,<0.13.0"]
build-backend = "uv_build"
